# Uncomment the next line to define a global platform for your project
 platform :osx, '10.10'

target 'iFeiBo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iFeiBo

  pod 'Alamofire', '~> 4.5'

end
